version: "1"

services:
  app:
    image: qushape:initfile
    stdin_open: false # equals docker run -i (interactive)
    tty: false   # equals docker run -t (terminal)
    build: .
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - $PWD:/data
